---
tasks:
  - name: command
    hosts: all
    routeros_command:
      commands: /system routerboard print
    register: system_print
    
  - name: debug print
    hosts: all
    debug: var=system_print.stdout_lines
